name: Minerobbers
version: '${project.version}'
main: me.lighty.minerobbers.MinerobbersPlugin
api-version: 1.19
depend: [ProtocolLib]
authors: [ Lighty ]
description: Minecraft Cops & Robbers Gamemode
commands:
  minerobbers:
    permission: minerobbers.command.minerobbers
    description: All commands for the Minerobbers gamemode.
  robbery:
    description: Start a robbery on an ATM or a store.
    permission: minerobbers.command.robbery